#!/bin/ruby

m,n = gets.strip.split(' ')
m = m.to_i
n = n.to_i
magazine = gets.strip
magazine = magazine.split(' ')
ransom = gets.strip
ransom = ransom.split(' ')

def code(m,n,magazine,ransom)
  
    mag_word_hash = Hash.new(0)
    ransom_note_hash = Hash.new(0)

    magazine.each { |word| mag_word_hash[word] += 1 }
    ransom.each { |word| ransom_note_hash[word] += 1 }

    if ransom_note_hash.all? { |word, count| mag_word_hash[word] >= ransom_note_hash[word] }
        puts "Yes"
    else
        puts "No"
    end 
end

code(m,n,magazine,ransom)
